homeassistant_container_name: homeassistant
homeassistant_image_name: homeassistant/home-assistant
homeassistant_image_version: stable

homeassistant_db_container_name: homeassistant-db
homeassistant_db_image_name: postgres
homeassistant_db_image_version: 14-alpine

homeassistant_db_user: homeassistant
homeassistant_db_password: set a secure password
homeassistant_db_name: homeassistant

homeassistant_data: "{{ homeserver_data }}/homeassistant"
homeassistant_data_db: "{{ homeassistant_data }}/db"
homeassistant_data_config: "{{ homeassistant_data }}/config"

homeassistant_http_subdomain: home
homeassistant_network_bridge: homeassistant_bridge
