- name: Start scanner_sftp
  block:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ scanner_sftp_data }}"
        state: directory
        recurse: true

    - name: Install sshd_config
      ansible.builtin.template:
        src: "sshd_config.j2"
        dest: "{{ scanner_sftp_data }}/sshd_config"
        owner: root
        group: root
        mode: 0644

    - name: Start scanner_sftp container
      community.docker.docker_container:
        name: "{{ scanner_sftp_container_name }}"
        image: "{{ scanner_sftp_image_name }}:{{ scanner_sftp_image_version }}"
        pull: true
        ports:
          - "{{ scanner_sftp_port }}:22"
        command: "{{ scanner_sftp_user }}:{{ scanner_sftp_password }}:{{ scanner_sftp_uid }}:{{ scanner_sftp_uid }}"
        restart_policy: unless-stopped
        volumes: "{{ scanner_sftp_volumes }}"
  tags:
    - scanner-sftp-start

- name: Stop scanner_sftp
  community.docker.docker_container:
    name: "{{ scanner_sftp_container_name }}"
    state: absent
  tags:
    - scanner-sftp-stop
    - stop
    - never
