watchtower_container_name: "watchtower"
watchtower_image_name: "containrrr/watchtower"
watchtower_image_version: "latest"

# Sets the 6 field cron schedule to use for checks and updates. This will check at 5am daily.
watchtower_cron_schedule: 0 0 5 * * *

watchtower_command: "--schedule '{{ watchtower_cron_schedule }}' --monitor-only"
watchtower_notification_url: ""
