- name: Start rustical
  block:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ rustical_data }}"
        state: directory
        recurse: true

    - name: Start rustical container
      community.docker.docker_container:
        name: "{{ rustical_container_name }}"
        image: "{{ rustical_image_name }}:{{ rustical_image_version }}"
        pull: true
        labels:
          traefik.enable: "true"
          http.subdomain: "{{ rustical_http_subdomain }}"
          traefik.http.routers.rustical.entrypoints: "{{ traefik_http_entrypoint }}"
        expose: [4000]
        restart_policy: unless-stopped
        networks:
          - name: "{{ homeserver_services_network }}"
        env:
          TZ: Europe/Berlin
          RUSTICAL_DATA_STORE__SQLITE__DB_URL: /var/lib/rustical/db.sqlite3

          RUSTICAL_FRONTEND__SECRET_KEY: "{{ rustical_frontend_secret }}"
          RUSTICAL_FRONTEND__ALLOW_PASSWORD_LOGIN: "false"
          RUSTICAL_OIDC__NAME: "Authelia"
          RUSTICAL_OIDC__ISSUER: "https://{{ authelia_http_subdomain }}.{{ homeserver_domain }}"
          RUSTICAL_OIDC__CLIENT_ID: "{{ rustical_oidc_client_id }}"
          RUSTICAL_OIDC__CLIENT_SECRET: "{{ rustical_oidc_client_secret }}"
          RUSTICAL_OIDC__CLAIM_USERID: "preferred_username"
          RUSTICAL_OIDC__SCOPES: '["openid", "profile", "groups"]'
          RUSTICAL_OIDC__REQUIRE_GROUP: "app:rustical"
          RUSTICAL_OIDC__ALLOW_SIGN_UP: "false"

          RUSTICAL_DAV_PUSH__ALLOWED_PUSH_SERVERS: "{{ rustical_davpush_allowed_servers | to_json }}"
        volumes:
          - "{{ rustical_data }}:/var/lib/rustical"
  tags:
    - rustical-start

- name: Stop rustical
  community.docker.docker_container:
    name: "{{ rustical_container_name }}"
    state: absent
  tags:
    - rustical-stop
    - stop
    - never
