- name: Start rustical
  block:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ rustical_data }}"
        state: directory
        recurse: true

    - name: Start rustical container
      community.docker.docker_container:
        name: "{{ rustical_container_name }}"
        image: "{{ rustical_image_name }}:{{ rustical_image_version }}"
        pull: true
        labels:
          traefik.enable: "true"
          http.subdomain: "{{ rustical_http_subdomain }}"
          traefik.http.routers.rustical.entrypoints: "{{ traefik_http_entrypoint }}"
        expose: [4000]
        restart_policy: unless-stopped
        networks:
          - name: "{{ homeserver_services_network }}"
        env:
          TZ: Europe/Berlin
          RUSTICAL_DATA_STORE__SQLITE__DB_URL: /var/lib/rustical/db.sqlite3
          RUSTICAL_AUTH__TOML__PATH: /etc/rustical/principals.toml
          RUSTICAL_FRONTEND__ENABLED: "false"
          RUSTICAL_FRONTEND__SECRET_KEY: "{{ rustical_frontend_secret }}"
          RUSTICAL_DAV_PUSH__ALLOWED_PUSH_SERVERS: "{{ rustical_davpush_allowed_servers | to_json }}"
        volumes:
          - "{{ rustical_data }}:/var/lib/rustical"
          - "{{ rustical_data }}:/etc/rustical/"
  tags:
    - rustical-start

- name: Stop rustical
  community.docker.docker_container:
    name: "{{ rustical_container_name }}"
    state: absent
  tags:
    - rustical-stop
    - stop
    - never
