- name: Start Prometheus
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: "{{ prometheus_data_config }}"
        state: directory
        recurse: true

    - name: Create data directory
      ansible.builtin.file:
        path: "{{ prometheus_data_data }}"
        state: directory
        recurse: true
        owner: nobody
        group: nogroup

    - name: Install configuration if not exists
      ansible.builtin.template:
        src: prometheus.yml
        dest: "{{ prometheus_data_config }}/prometheus.yml"
        force: false

    - name: Start prometheus container
      community.docker.docker_container:
        name: "{{ prometheus_container_name }}"
        image: "{{ prometheus_image_name }}:{{ prometheus_image_version }}"
        pull: true
        labels:
          traefik.enable: "true"
          http.subdomain: "{{ prometheus_http_subdomain }}"
          traefik.http.routers.prometheus.entrypoints: "{{ traefik_http_entrypoint }}"
          homepage.group: Admin
          homepage.name: Prometheus
          homepage.href: "https://{{ prometheus_http_subdomain }}.{{ homeserver_domain }}"
        expose: [9090]
        restart_policy: unless-stopped
        networks:
          - name: "{{ traefik_network }}"
        env:
          TZ: Europe/Berlin
        command:
          - --config.file=/etc/prometheus/prometheus.yml
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - "{{ prometheus_data_data }}:/prometheus"
          - "{{ prometheus_data_config }}:/etc/prometheus:ro"
  tags:
    - prometheus-start

- name: Stop Prometheus
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    state: absent
  tags:
    - prometheus-stop
    - stop
    - never
