- name: Start Traefik
  block:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ traefik_data }}"
        state: directory
        recurse: true
      loop:
        - "{{ traefik_data_letsencrypt }}"
        - "{{ traefik_data_config }}"
        - "{{ traefik_data_config }}/dynamic"
        - "{{ traefik_data_logs }}"
    
    - name: Install traefik.yml
      ansible.builtin.template:
        src: traefik.yml
        dest: "{{ traefik_data_config }}/traefik.yml"
        # Default delimeters interfere with Go's tempating engine :/
        variable_start_string: "[%"
        variable_end_string: "%]"

    - name: Start traefik container
      community.docker.docker_container:
        name: "{{ traefik_container_name }}"
        image: "{{ traefik_image_name }}:{{ traefik_image_version }}"
        dns_servers:
          - 1.1.1.1
          - 1.0.0.1
        env: "{{ traefik_env }}"
        ports:
          - 80:80/tcp
          - 443:443/tcp
          - 443:443/udp
        pull: true
        expose: [80]
        restart_policy: unless-stopped
        networks:
          - name: "{{ homeserver_services_network }}"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "{{ traefik_data_letsencrypt }}/:/letsencrypt"
          - "{{ traefik_data_config }}/:/etc/traefik:ro"
          - "{{ traefik_data_logs }}/:/logs"
  tags:
    - traefik-start

- name: Stop Traefik
  community.docker.docker_container:
    name: "{{ traefik_container_name }}"
    state: absent
  tags:
    - traefik-stop
    - stop
    - never
