- name: Install service
  tags:
    - hdd-apm-start
  template:
    src: "hdd-apm.service.j2"
    dest: "/etc/systemd/system/hdd-apm.service"
    owner: root
    group: root
    mode: 0644
  when: hdd_apm_level and hdd_apm_disks

- name: Enable service
  tags:
    - hdd-apm-start
  systemd:
    name: hdd-apm.service
    enabled: true

- name: Disable service
  tags:
    - hdd-apm-stop
    - stop
    - never
  systemd:
    name: hdd-apm.service
    state: stopped
    enabled: false
