immich_image_version: release

# Queue management for immich_microservices
immich_redis_container_name: immich-redis
immich_redis_image_name: redis
immich_redis_image_version: "6.2"

# persistent data
immich_db_container_name: immich-db
immich_db_image_name: tensorchord/pgvecto-rs
immich_db_image_version: pg14-v0.2.0

# Run Machine Learning models
immich_ml_container_name: immich-machine_learning
immich_ml_image_name: ghcr.io/immich-app/immich-machine-learning
immich_ml_image_version: "{{ immich_image_version }}"

# Handles REST API requests
immich_server_container_name: immich-server
immich_server_image_name: ghcr.io/immich-app/immich-server
immich_server_image_version: "{{ immich_image_version }}"

# Immich config environment variables
# see https://immich.app/docs/install/environment-variables
immich_general_tz: Europe/Berlin # microservices
immich_general_log_level: log # server, microservices
immich_general_public_login_page_message: "" # web

immich_geocoding_disable_reverse_geocoding: "false" # microservices
immich_geocoding_reverse_geocoding_precision: "3" # microservices

immich_db_username: immich # server, microservices
immich_db_password: supersecretpassword # server, microservices
immich_db_database: immich # server, microservices

immich_data: "{{ homeserver_data }}/immich"
immich_data_upload: "{{ immich_data }}/library"
immich_data_db: "{{ immich_data }}/db"
immich_data_redis: "{{ immich_data }}/redis"
immich_data_ml_cache: "{{ immich_data }}/ml_cache"

immich_http_subdomain: immich

immich_network_bridge: immich_bridge

immich_volumes:
  - "{{ immich_data_upload }}:/usr/src/app/upload"
  - "{{ immich_data }}/immich.yml:/immich.yml:ro"
